#! /bin/bash
if [[($1 = "")]]
then
	echo "enter dir";
fi
# files=`ls -la $1 | grep "^p"`;
files=`ls -la $1 | grep "^-" | awk '{print $9}' | sort `;
#  fuser  returns a non-zero return code if none of the specified files is accessed or in case of a fatal error.  If at least one access has  been found, fuser returns zero.

echo "" > tmp;
for file in $files
do
	if [[(${1: -1} = "/")]]
	then
		filename="$1$file";
	else
		filename="$1/$file"
	fi
	# echo $filename;
	is_user=`fuser -v $filename 2>tmp`;
	if [[($is_used != 0)]]
	then	
		res=`cat tmp | grep "  F"`;
		if [[($? = 0)]]
		then
			echo $file;
		fi
	fi
done
