#! /bin/bash

ERROR_PATH="$HOME/lab1_err"
ERROR_MSG="Something went wrong. Check your input."

# lists all users who have read access to a directory
list_r_users() {
        dir=$1;
        if [[(! -d "$dir")]] # -d is a operator to test if the given directory exists or not. "File test operators" -> google
                then
                        echo "$dir is not a directory"
                else
                        rights=`ls -l | grep $dir | awk '{print $1}'`;
                        owner=`ls -l | grep $dir | awk '{print $3}'`;
                        group=`ls -l | grep $dir | awk '{print $4}'`;  
                        if [[(${rights:1:1} = r)]]
                        then
                                echo $owner;
                        fi
                        if [[(${rights:4:1} = r)]]
                        then
                                for user in `getent passwd`
                                do
                                        username=`echo $user | awk -F: '{print $1}'`
                                        usergroup=`groups $username 2>$ERROR_PATH | grep -w $group`
                                        if [[ -n $usergroup && -z `echo $username | grep -w $owner` ]]
                                        then
                                                echo $username
                                        fi
                                done
                        fi
                        if [[(${rights:7:1} = r)]]
                        then
                                for user in `getent passwd | tr ' ' '_'`
                                do
                                        username=`echo $user | awk -F: '{print $1}'`
                                        usergroup=`groups $username | grep -w $group`
                                        if [[ -z $usergroup && -z `echo $username | grep -w $owner` ]]
                                        then
                                                echo $username
                                        fi
                                done
                        fi
        fi
        return;
}

# lists all users who have write access to a directory
list_w_users() {
        dir=$1; 
        if [[(! -d "$dir")]]
                then    
                        echo "$dir is not a directory">$2
                else    
                        rights=`ls -l | grep $dir | awk '{print $1}'`;
                        owner=`ls -l | grep $dir | awk '{print $3}'`;
                        group=`ls -l | grep $dir | awk '{print $4}'`;  
                        if [[(${rights:2:1} = w)]]
                        then
                                echo $owner;
                        fi
                        if [[(${rights:5:1} = w)]]
                        then
                                for user in `getent passwd`
                                do
                                        username=`echo $user | awk -F: '{print $1}'` 
                                        usergroup=`groups $username 2>>$ERROR_PATH | grep -w $group`
                                        if [[ -n $usergroup && -z `echo $username | grep -w $owner` ]]
                                        then
                                                echo $username
                                        fi
                                done
                        fi
                        if [[(${rights:8:1} = w)]]
                        then
                                for user in `getent passwd | tr ' ' '_'`
                                do
                                        username=`echo $user | awk -F: '{print $1}'` 
                                        usergroup=`groups $username 2>>$ERROR_PATH | grep -w $group`
                                        if [[ -z $usergroup && -z `echo $username | grep -w $owner` ]]
                                        then
                                                echo $username
                                        fi
                                done
                        fi
        fi
        return;
}

